"""Initial migration

Revision ID: c74a142862d3
Revises: 
Create Date: 2025-03-23 14:03:47.879095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c74a142862d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ohlc_data', 'ticker',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=False)
    # Keeping the timestamp column as it is (do not alter type)
    op.alter_column('ohlc_data', 'open',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('ohlc_data', 'high',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('ohlc_data', 'low',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('ohlc_data', 'close',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('ohlc_data', 'volume',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # Do not drop important indexes
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate necessary indexes
    op.create_index('ohlc_data_timestamp_idx', 'ohlc_data', [sa.text('timestamp DESC')], unique=False)
    op.create_index('ohlc_data_id_idx', 'ohlc_data', ['id', 'timestamp'], unique=True)
    op.alter_column('ohlc_data', 'volume',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('ohlc_data', 'close',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('ohlc_data', 'low',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('ohlc_data', 'high',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('ohlc_data', 'open',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # Do not alter the timestamp column type (avoid partitioning issues)
    op.alter_column('ohlc_data', 'ticker',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
